[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pollen"
authors = [
    { name = "Susan Garry", email = "shg64@cs.cornell.edu" }
]
readme = "README.md"
dynamic = ["version", "description"]

[project.scripts]
exine = "pollen.main:main"
