name: build

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  test-py:
    name: test Python tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: |
              mygfa/pyproject.toml
              pollen_data_gen/pyproject.toml
              pollen_py/pyproject.toml
              slow_odgi/pyproject.toml

      - name: Install Flit
        run: pip install flit

      - name: Install mygfa
        run: cd mygfa ; flit install --symlink
      - name: Install pollen_data_gen
        run: cd pollen_data_gen ; flit install --symlink
      - name: Install pollen_py
        run: cd pollen_py ; flit install --symlink
      - name: Install slow_odgi
        run: cd slow_odgi ; flit install --symlink

      - name: Install Turnt
        run: pip install turnt

      - name: Problem matcher
        run: echo '::add-matcher::.github/tap-matcher.json'

      - name: Fetch test data
        run: make fetch SMALL=1

      - name: Pull odgi container
        run: |
          docker pull quay.io/biocontainers/odgi:0.8.3--py310h6cc9453_0
          docker tag quay.io/biocontainers/odgi:0.8.3--py310h6cc9453_0 odgi

      - name: Install odgi alias
        run: |
          mkdir -p $HOME/.local/bin
          cp .github/odgi.sh $HOME/.local/bin/odgi
          chmod a+x $HOME/.local/bin/odgi

      # Test slow_odgi.
      - name: Set up for slow_odgi tests
        run: make slow-odgi-setup SMALL=1
      - name: Test slow_odgi
        run: make test-slow-odgi SMALL=1

  test-parser:
    name: test DSL parser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install runt
      - run: cargo build
        working-directory: ./pollen
      - run: runt -v
        working-directory: ./pollen
