name: build

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: |
              mygfa/pyproject.toml
              pollen_data_gen/pyproject.toml
              pollen_py/pyproject.toml
              slow_odgi/pyproject.toml

      - name: Install Flit
        run: pip install flit

      - name: Install mygfa
        run: cd mygfa ; flit install --symlink
      - name: Install pollen_data_gen
        run: cd pollen_data_gen ; flit install --symlink
      - name: Install pollen_py
        run: cd pollen_py ; flit install --symlink
      - name: Install slow_odgi
        run: cd slow_odgi ; flit install --symlink

      - name: Install Turnt
        run: pip install turnt

      - name: Problem matcher
        run: echo '::add-matcher::.github/tap-matcher.json'

      - name: Fetch test data
        run: make fetch

      - name: Pull odgi container
        run: |
          docker pull quay.io/biocontainers/odgi:0.8.3--py310h6cc9453_0
          docker tag quay.io/biocontainers/odgi:0.8.3--py310h6cc9453_0 odgi

      - name: Install odgi alias
        run: |
          mkdir -p ~/.local/bin
          echo '#!/bin/sh\ndocker run --rm odgi odgi $@' > ~/.local/bin/odgi
          chmod a+x ~/.local/bin/odgi
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo $PATH

      - name: Set up for slow_odgi tests
        run: make slow-odgi-setup

      - name: Test slow_odgi
        run: make test-slow-odgi
