name: build

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: |
              mygfa/pyproject.toml
              pollen_data_gen/pyproject.toml
              pollen_py/pyproject.toml
              slow_odgi/pyproject.toml

      - name: Install Flit
        run: pip install flit

      - name: Install mygfa
        run: cd mygfa ; flit install --symlink
      - name: Install pollen_data_gen
        run: cd pollen_data_gen ; flit install --symlink
      - name: Install pollen_py
        run: cd pollen_py ; flit install --symlink
      - name: Install slow_odgi
        run: cd slow_odgi ; flit install --symlink

      - name: Install Turnt
        run: pip install turnt

      - name: Problem matcher
        run: echo '::add-matcher::.github/tap-matcher.json'

      - name: Fetch test data
        run: make fetch

      - name: Set up for slow_odgi tests
        run: make slow-odgi-setup
        uses: docker://quay.io/biocontainers/odgi

      - name: Test slow_odgi
        run: make test-slow-odgi
