name: CodeQuality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CodeQuality
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install "black<23" mypy==v0.902
    - run: black --diff --check $(git ls-files '*.py')
    - run: mypy $(git ls-files '*.py')
