name: quality
on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python
    steps:
    - uses: actions/checkout@v4

    - name: ruff check
      uses: astral-sh/ruff-action@v3
      with:
        src: >-
          mygfa
          slow_odgi
          pollen_data_gen
          flatgfa-py

    - name: ruff format
      uses: astral-sh/ruff-action@v3
      with:
        args: "format --check --diff"
        src: >-
          mygfa
          slow_odgi
          pollen_data_gen
          flatgfa-py

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: mypy
      run: MYPYPATH=mygfa uv tool run mypy --no-namespace-packages --disallow-untyped-defs mygfa slow_odgi pollen_data_gen
