name: docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Permissions for GitHub pages deployment.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Sphinx.
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - run: pip install Sphinx
      - name: "Sphinx problem matcher"
        uses: sphinx-doc/github-problem-matcher@master

      # Docs for mygfa.
      - name: Build mygfa docs
        run: |
          cd mygfa/docs
          make html

      # Docs for flatgfa-py.
      - name: Build flatgfa-py
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --manifest-path flatgfa-py/Cargo.toml
      - name: Build flatgfa-py docs
        run: |
          cd flatgfa-py/docs
          make html

      # Create site.
      - name: Assemble site directory
        run: |
          mkdir -p site
          cp -r mygfa/docs/_build/html site/mygfa
          cp -r flatgfa-py/docs/_build/html site/flatgfa
      - name: Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{github.event_name=='push' && github.ref=='refs/heads/main' && github.repository_owner=='cucapra'}}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
